import QRCode from "qrcode";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { shareLinks } from "@/lib/db/schema";
import { limiters, clientIp } from "@/lib/ratelimit";
import { siteUrl } from "@/lib/site";

/**
 * SVG QR for a share link. Generated by us from a URL we control — never from
 * user input — so serving it inline as an image is safe. Immutable: a new code
 * is a new URL.
 */
export async function GET(req: Request, { params }: { params: Promise<{ code: string }> }) {
  if (!(await limiters.redirect.limit(clientIp(req))).success) return new Response("Too many requests", { status: 429 });

  const { code } = await params;
  if (!/^[a-z0-9]{6,12}$/.test(code)) return new Response("Not found", { status: 404 });

  const [link] = await db.select({ id: shareLinks.id }).from(shareLinks).where(eq(shareLinks.code, code)).limit(1);
  if (!link) return new Response("Not found", { status: 404 });

  const svg = await QRCode.toString(siteUrl(`/r/${code}`), {
    type: "svg",
    margin: 1,
    width: 512,
    errorCorrectionLevel: "M",
    color: { dark: "#13294b", light: "#ffffff" },
  });

  return new Response(svg, {
    headers: {
      "content-type": "image/svg+xml; charset=utf-8",
      "content-disposition": `inline; filename="${code}.svg"`,
      "cache-control": "public, max-age=31536000, immutable",
    },
  });
}
